#to start docker deamon
#open -a Docker

version: '3.11'
#sudo docker-compose build

services:
  app:
    user: "${USER_ID:-1000}"   # environment variable uid
    hostname: "${HOST:-Rahul}" # hostname of the container
    image: rahul-template   # image to be called
    container_name : rahul-template-container
    build:
      context : .
      dockerfile : ./docker/Dockerfile # where is the docker file
      # below args to be pased in docerfile check docer file
      args:
        USER_NAME : "${USER_NAME:-rahulsm.27}"
        USER_ID : "${USER_ID:-1000}"

   # env_file:
    #  - .envs/.app

    volumes : # during project building we are going to mount our project directory to docker container so that changes done in project is avialable in docker
      - ./:/app/
      - ~/.config/gcloud:${HOME}/.config/gcloud
  # gclodu credentials mapped to docker container so that automatically authenticated in container
    ports :
      - 8080:8080

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count : all 
              capabilities : [gpu]

    ipc : host
    init : true
